---
- name: Get the supported resource modules
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
  register: resource_manager_network_resources_list

- name: Set default resources
  ansible.builtin.set_fact:
    resource_manager_resources: "{{ resource_manager_network_resources_list['modules'] }}"
  when: resource_manager_resources is undefined

- name: Set Network resources
  ansible.builtin.set_fact:
    resource_manager_network_resources: "{{ resource_manager_network_resources_list['modules'] | ansible.utils.param_list_compare(resources) }}"

- name: Resolve inventory
  ansible.builtin.include_tasks: includes/inventory.yaml

- name: Include retrieve tasks
  ansible.builtin.include_tasks: includes/retrieve.yaml
  when: data_store['scm'] is defined

- name: Include build tasks
  ansible.builtin.include_tasks: includes/build.yaml
  loop: "{{ resource_manager_network_resources['actionable'] }}"
  loop_control:
    loop_var: res

- name: Include build tasks
  ansible.builtin.include_tasks: includes/remote_publish.yaml
  when: data_store.scm.origin is defined
