---
- name: Set default host vars path
  ansible.builtin.set_fact:
    resource_manager_inventory_directory: "."
  when: data_store.local is not defined

- name: Set default host vars path
  ansible.builtin.set_fact:
    resource_manager_inventory_directory: "{{ data_store['local'] }}"
  when: data_store['local'] is defined

- name: Set default path
  ansible.builtin.set_fact:
    resource_manager_inventory_path: "{{ resource_manager_repository['path'] }}"
  when: resource_manager_repository is defined

- name: Set default path
  ansible.builtin.set_fact:
    resource_manager_inventory_path: "{{ resource_manager_inventory_directory }}"
  when: resource_manager_repository is not defined
