---
- name: Include build tasks
  ansible.builtin.include_tasks: includes/publish_tag.yaml
  when: data_store.scm.origin.tag is defined

- name: Include build tasks
  ansible.builtin.include_tasks: includes/publish.yaml
  when: data_store.scm.origin.tag is not defined
